### ISSUE TITLE
Unable to parse your GitHub user and repository from 'https://github.com/kshamiev/testXml'. Please open an issue on https://github.com/fgrehm/previewdocs

### ISSUE THREAD

**Issue by kshamiev** [fgrehm/previewdocs#8]

**Comment by fgrehm** [comment]
Thanks for reporting the issue, the problem is that your git remote origin does not end with a `.git` [as expected by the CLI](https://github.com/fgrehm/previewdocs/blob/349b9f92115e87cd80e17ffd52ab3836a63bca8d/previewdocs.go#L131). I'll try to fix it when I have a chance but in the meantime you should be able to make things work by changing your git config appending a trailing `.git` to the URL specified (https://github.com/kshamiev/testXml.git). If you need help with that just LMK

**Comment by kshamiev** [comment]
ok
